# Generated by Django 3.0.6 on 2020-05-29 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_auto_20200529_1957'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tao_vao', models.DateTimeField(auto_now_add=True)),
                ('cap_nhat_vao', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTrongGioHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_origin.GioHang')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Sach')),
            ],
        ),
    ]
