# Generated by Django 3.0.7 on 2020-07-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_origin', '0002_auto_20200602_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='tao_vao',
            field=models.DateTimeField(),
        ),
    ]
