# Generated by Django 3.0.7 on 2020-07-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_origin', '0003_auto_20200702_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtronggiohang',
            name='gio_hang',
        ),
        migrations.RemoveField(
            model_name='itemtronggiohang',
            name='item',
        ),
        migrations.DeleteModel(
            name='GioHang',
        ),
        migrations.DeleteModel(
            name='ItemTrongGioHang',
        ),
    ]
