# Generated by Django 3.0.7 on 2020-07-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_origin', '0005_giohang_itemtronggiohang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtronggiohang',
            name='gio_hang',
        ),
        migrations.RemoveField(
            model_name='itemtronggiohang',
            name='item',
        ),
        migrations.RemoveField(
            model_name='giohang',
            name='cap_nhat_vao',
        ),
    ]
