# Generated by Django 3.0.7 on 2020-07-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_origin', '0006_auto_20200707_1553'),
        ('order', '0005_auto_20200707_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemTrongGioHang',
        ),
    ]
