# Generated by Django 3.0.6 on 2020-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200608_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhanguser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='khachhanguser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='diachikhachhang',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='diachikhachhang',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='diachikhachhang',
            unique_together=set(),
        ),
    ]
