# Generated by Django 3.0.7 on 2020-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='anh_minh_hoa',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='loai_voucher',
        ),
        migrations.AddField(
            model_name='voucher',
            name='image',
            field=models.ImageField(null=True, upload_to='vouchers/2020/7'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='ngay_bat_dau',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='ngay_het_han',
            field=models.DateTimeField(),
        ),
    ]
