# Generated by Django 3.0.7 on 2020-06-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='loai_voucher',
        ),
    ]
