# Generated by Django 3.0.7 on 2020-07-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_auto_20200629_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='image',
            field=models.ImageField(null=True, upload_to='vouchers/2020/7'),
        ),
    ]
