# Generated by Django 3.0.6 on 2020-05-29 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_giao_hang', models.CharField(default='', max_length=15)),
                ('thoi_gian_dat_hang', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.IntegerField(choices=[(0, 'Chờ duyệt...'), (1, 'Chấp nhận'), (2, 'Bị admin từ chối'), (3, 'Bị khách hàng hủy'), (4, 'Đang giao...'), (5, 'Đã giao xong!')], default=0)),
                ('phuong_thuc_giao_hang', models.CharField(default='', max_length=50)),
                ('dia_chi_giao_hang', models.CharField(default='', max_length=255)),
                ('phi_ship', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.GioHang')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.Voucher')),
            ],
        ),
    ]
