# Generated by Django 3.0.6 on 2020-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='phuong_thuc_giao_hang',
            field=models.IntegerField(choices=[(0, 'Giao hàng nhanh'), (1, 'Giao hàng tiết kiệm'), (2, 'Bưu điện')], default=0),
        ),
    ]
