# Generated by Django 3.0.7 on 2020-07-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200620_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='cart',
        ),
        migrations.AddField(
            model_name='donhang',
            name='so_luong',
            field=models.IntegerField(default=0),
        ),
    ]
