# Generated by Django 3.0.7 on 2020-07-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200702_1723'),
        ('user', '0003_auto_20200609_1743'),
        ('order', '0004_auto_20200702_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='items',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='phuong_thuc_giao_hang',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='thoi_gian_giao_hang',
        ),
        migrations.AddField(
            model_name='donhang',
            name='total',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='dia_chi_giao_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.DiaChiKhachHang'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='phi_ship',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='thoi_gian_dat_hang',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ItemTrongDonHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.DonHang')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Sach')),
            ],
        ),
    ]
