# Generated by Django 3.0.7 on 2020-07-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_origin', '0002_auto_20200602_2151'),
        ('order', '0004_auto_20200701_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart_origin.GioHang'),
        ),
    ]
