# Generated by Django 3.0.7 on 2020-07-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200609_1743'),
        ('order', '0005_auto_20200707_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='dia_chi_giao_hang',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.DiaChiKhachHang'),
        ),
    ]
