# Generated by Django 3.0.7 on 2020-07-02 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart_origin', '0003_auto_20200702_1037'),
        ('order', '0005_donhang_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='so_luong',
        ),
        migrations.AddField(
            model_name='donhang',
            name='tao_vao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Tạo vào'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donhang',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart_origin.ItemTrongGioHang'),
        ),
    ]
