# Generated by Django 3.0.7 on 2020-07-02 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_origin', '0003_auto_20200702_1037'),
        ('order', '0006_auto_20200702_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='tao_vao',
        ),
        migrations.AlterField(
            model_name='donhang',
            name='cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart_origin.GioHang'),
            preserve_default=False,
        ),
    ]
