# Generated by Django 3.0.7 on 2020-07-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200702_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='phi_ship',
            field=models.IntegerField(default=12000),
        ),
    ]
