# Generated by Django 3.0.7 on 2020-07-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart_origin', '0003_auto_20200702_1037'),
        ('order', '0008_auto_20200702_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart_origin.ItemTrongGioHang'),
        ),
    ]
