# Generated by Django 3.0.7 on 2020-07-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200702_1227'),
        ('order', '0009_donhang_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='items',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='phuong_thuc_giao_hang',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='thoi_gian_giao_hang',
        ),
        migrations.AlterField(
            model_name='donhang',
            name='thoi_gian_dat_hang',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ItemTrongDonHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.DonHang')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Sach')),
            ],
        ),
    ]
