# Generated by Django 3.0.7 on 2020-07-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200702_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='total',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='phi_ship',
            field=models.IntegerField(default=12),
        ),
    ]
