# Generated by Django 3.0.6 on 2020-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='cap_nhat_vao',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật vào'),
        ),
        migrations.AlterField(
            model_name='giohang',
            name='tao_vao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tạo vào'),
        ),
    ]
