# Generated by Django 3.0.6 on 2020-05-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='', max_length=255)),
                ('slug', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(default='', max_length=255)),
                ('tac_gia', models.CharField(default='', max_length=255)),
                ('nxb', models.CharField(default='', max_length=255)),
                ('nam_xb', models.IntegerField(default=0)),
                ('mo_ta', models.TextField(default='')),
                ('hinh_anh', models.CharField(default='', max_length=255)),
                ('so_luong_con', models.IntegerField(default=0)),
                ('so_luong_nhap', models.IntegerField(default=0)),
                ('don_gia', models.IntegerField(default=0)),
                ('loai_sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.LoaiSach')),
            ],
        ),
        migrations.CreateModel(
            name='DotNhapSach',
            fields=[
                ('id_sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='book.Sach')),
                ('ngay_nhap', models.CharField(max_length=15)),
                ('so_luong', models.IntegerField(default=0)),
                ('gia_nhap', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('id_sach', 'ngay_nhap')},
            },
        ),
    ]
