# Generated by Django 3.0.6 on 2020-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaisach',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, unique=True),
        ),
    ]
