# Generated by Django 3.0.6 on 2020-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200529_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaisach',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sach',
            name='hinh_anh',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='img/news/2020/6', verbose_name='Ảnh bìa'),
        ),
    ]
