# Generated by Django 3.0.7 on 2020-06-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200612_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sach',
            old_name='ten',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sach',
            name='don_gia',
        ),
        migrations.RemoveField(
            model_name='sach',
            name='hinh_anh',
        ),
        migrations.AddField(
            model_name='sach',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='sach',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
