# Generated by Django 3.0.7 on 2020-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200612_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='hinh_anh',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='books/2020/7', verbose_name='Ảnh bìa'),
        ),
    ]
