# Generated by Django 3.0.7 on 2020-06-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200620_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
