# Generated by Django 3.0.7 on 2020-07-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200627_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sach',
            old_name='price',
            new_name='don_gia',
        ),
        migrations.RenameField(
            model_name='sach',
            old_name='image',
            new_name='hinh_anh',
        ),
        migrations.RenameField(
            model_name='sach',
            old_name='name',
            new_name='ten',
        ),
    ]
